name: CU Test
favicon: null
layout_spectrum: 0.24881562311202288
typography_spectrum: 0.5425765467807651
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.48791663465090096
  lightness: 0.8227990644518286
  saturation: 0.8758143265731633
  rhythmicContrast: 0.8820690216962248
purpose: []
